---

- name: enable and restart NetworkManager
  listen: restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted
    enabled: yes

- name: enable and restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes
