---

- name: create main user
  user:
    name: "{{ main_user }}"
    shell: /bin/zsh
    create_home: yes
    groups: "{{ user_groups }}"
    append: yes

- name: add main user to sudoers
  copy:
    dest: /etc/sudoers.d/saumon-user
    content: |
      {{ main_user }} ALL=(ALL) ALL
    validate: 'visudo -csf %s'

- name: check SSH key presence
  become_user: "{{ main_user }}"
  stat:
    path: ~/.ssh/id_{{ main_user_key_type }}
  register: ssh_key_file

- name: generate SSH key
  become_user: "{{ main_user }}"
  openssh_keypair:
    path: ~/.ssh/id_{{ main_user_key_type }}
    type: "{{ main_user_key_type }}"
    comment: "{{ main_user }}-{{ ansible_date_time.year }}-{{ ansible_date_time.month }}@{{ inventory_hostname }}"
  when: not ssh_key_file.stat.exists

- name: init GPG
  become_user: "{{ main_user }}"
  command: gpg --list-keys
  when: not ansible_check_mode

- name: create home directories
  become_user: "{{ main_user }}"
  file:
    path: ~/{{ item }}
    state: directory
  loop: "{{ user_directories }}"

- name: set default terminal for Nemo
  shell: "gsettings set org.cinnamon.desktop.default-applications.terminal exec urxvtc"

- name: set command exec argument for Nemo terminal
  shell: "gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg -e"

- name: set Nemo as default file manager
  shell: "xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search"

- import_tasks: dotfiles.yml
