---

- name: create main user
  user:
    name: "{{ main_user }}"
    shell: /bin/zsh
    create_home: yes
    groups: ["docker", "lp", "input"]
    append: yes

- name: add main user to sudoers
  lineinfile:
    path: /etc/sudoers
    line: '{{ main_user }} ALL=(ALL) ALL'
    insertafter: '^root ALL=.*'
    validate: 'visudo -cf %s'

- name: generate SSH key
  become_user: "{{ main_user }}"
  openssh_keypair:
    path: ~/.ssh/id_{{ main_user_key_type }}
    type: "{{ main_user_key_type }}"
    comment: "{{ main_user }}-{{ ansible_date_time.year }}-{{ ansible_date_time.month }}@{{ inventory_hostname }}"

- name: init GPG
  become_user: "{{ main_user }}"
  command: gpg --list-keys
  when: not ansible_check_mode

- name: create home directories
  become_user: "{{ main_user }}"
  file:
    path: ~/{{ item }}
    state: directory
  loop: "{{ user_directories }}"
