---

- name: template WPA2/PSK wifi networks
  template:
    src: wpa.nmconnection
    dest: /etc/NetworkManager/system-connections/{{ item.name }}.nmconnection
    mode: '600'
  loop: "{{ wifi_networks_wpa }}"
  notify: restart NetworkManager

- name: template EAP/enterprise wifi networks
  template:
    src: eap.nmconnection
    dest: /etc/NetworkManager/system-connections/{{ item.name }}.nmconnection
    mode: '600'
  loop: "{{ wifi_networks_eap }}"
  notify: restart NetworkManager
