---

- name: install necessary bluetooth packages
  yay:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ bluetooth_packages }}"

- name: enable bluetooth driver at boot
  lineinfile:
    path: /etc/bluetooth/main.conf
    line: 'AutoEnable=true'
    regexp: '#?^AutoEnable ?= ?.*$'
    state: present

- name: enable bluetooth service at boot
  systemd:
    name: bluetooth.service
    enabled: yes
