---

- name: install necessary bluetooth packages
  become_user: "{{ main_user }}"
  yay:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ bluetooth_packages }}"

- name: enable bluetooth driver at boot
  lineinfile:
    path: /etc/bluetooth/main.conf
    line: 'AutoEnable=true'
    regexp: '#?^AutoEnable ?= ?.*$'
    state: present

- name: enable bluetooth service at boot
  systemd:
    name: bluetooth.service
    enabled: yes

- name: add main user to wheel group
  user:
    name: "{{ main_user }}"
    append: yes
    groups:
      - wheel

- name: set blueman polkit rules
  copy:
    src: polkit-blueman.rules
    dest: /etc/polkit-1/rules.d/51-blueman.rules
    mode: 0644
