---

- name: install required packages
  become_user: "{{ main_user }}"
  yay:
    name: "{{ item }}"
  loop: "{{ print_packages }}"

- name: add user to lp group
  user:
    name: "{{ main_user }}"
    groups: ["lp"]
    append: yes

- name: start and enable cups service
  systemd:
    daemon_reload: yes
    name: org.cups.cupsd.service
    state: started
    enabled: yes
