---

- name: install required packages
  become_user: "{{ main_user }}"
  yay:
    name: "{{ item }}"
  loop: "{{ print_packages }}"

- name: add user to lp group
  user:
    name: "{{ main_user }}"
    groups: ["lp"]
    append: yes

- name: enable cups service at boot
  systemd:
    daemon_reload: yes
    name: org.cups.cupsd.service
    state: stopped
    enabled: "{{ print_cups_enabled }}"
