---

boot_loader_entries:

  - name: Arch Linux
    linux: /vmlinuz-linux
    initrd: /initramfs-linux.img
    options: >-
      cryptdevice=UUID=385b759e-e8c1-4cce-99b4-a23bd167956d:poissonnerie
      root=/dev/mapper/vg0-root
      rw
      nowatchdog
      systemd.restore_state=0
    intel_ucode: true
    default: false

  - name: Arch Linux LTS
    linux: /vmlinuz-linux-lts
    initrd: /initramfs-linux-lts.img
    options: >-
      cryptdevice=UUID=385b759e-e8c1-4cce-99b4-a23bd167956d:poissonnerie
      root=/dev/mapper/vg0-root
      rw
      nowatchdog
      systemd.restore_state=0
    intel_ucode: true
    default: true

boot_loader_timeout: 1 # seconds

boot_efi_path: /boot
