---

#
# Font packages are in `packages.yml`
#

fonts_windows_pkg_name: ttf-ms-win10

fonts_windows_pkg_url: "https://dl.saumon.io/{{ fonts_windows_pkg_name }}.pkg.tar.xz"

fonts_windows_tmp_file: "/tmp/{{ fonts_windows_pkg_name }}.pkg.tar.xz"
