---

- name: install necessary network packages
  become_user: "{{ main_user }}"
  yay:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ network_packages }}"

- import_tasks: dns.yml
