---

- name: install necessary network packages
  become_user: "{{ main_user }}"
  yay:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ network_packages }}"

- import_tasks: dns.yml

- name: copy NM dispatcher scripts
  copy:
    src: "dispatcher.d/{{ item }}"
    dest: "/etc/NetworkManager/dispatcher.d/{{ item }}"
  loop: "{{ network_dispatcher_scripts }}"

- import_tasks: networks.yml
  tags: ['wifi']
