---

- name: install nftables
  yay:
    name: nftables
    state: present

- name: copy nftables configuration
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
  notify: apply nftables config

- name: enable and start nftables
  systemd:
    name: nftables
    state: started
    enabled: yes
