---

# Mandatory
resolution_type: GETDNS_RESOLUTION_STUB

# Use TLS
dns_transport_list:
  - GETDNS_TRANSPORT_TLS

# Use only TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED

# Recommended
tls_query_padding_blocksize: 128

# Recommended
edns_client_subnet_private : 1

# Use multiple upstreams at once
round_robin_upstreams: 1

# TLS connections keep-alive timeout
idle_timeout: 10000

# Timeout of an individual request
timeout: 3000

listen_addresses:
  - 127.0.0.1@{{ network_stubby_port }}
  - 0::1@{{ network_stubby_port }}

appdata_dir: "/var/cache/stubby"

upstream_recursive_servers:
{% for resolver in network_dot_resolvers %}
  - address_data: {{ resolver.address_data }}
    tls_auth_name: "{{ resolver.tls_auth_name }}"
{% endfor %}
