---

- import_playbook: i18n.yml
- import_playbook: hostname.yml
- import_playbook: systemd.yml
- import_playbook: pacman.yml
- import_playbook: aur.yml
- import_playbook: boot.yml
- import_playbook: packages.yml
- import_playbook: user.yml
- import_playbook: fonts.yml
- import_playbook: graphical.yml
- import_playbook: network.yml
- import_playbook: firewall.yml
- import_playbook: bluetooth.yml
- import_playbook: pulseaudio.yml
- import_playbook: print.yml
- import_playbook: laptop-stats.yml
