---

- name: "download {{ fonts_windows_pkg_name }} package"
  get_url:
    url: "{{ fonts_windows_pkg_url }}"
    dest: "{{ fonts_windows_tmp_file }}"

- name: "remove old {{ fonts_windows_pkg_name }} package"
  pacman:
    name: "{{ fonts_windows_pkg_name }}"
    state: absent

- name: "install {{ fonts_windows_pkg_name }} package"
  pacman:
    name: "{{ fonts_windows_tmp_file }}"
    state: installed
  when: not ansible_check_mode

- name: clean up file
  file:
    path: "{{ fonts_windows_tmp_file }}"
    state: absent
